/** Fixed English labels for invoice document output (preview, PDF, Excel, print). */
export const INVOICE_DOCUMENT_LABELS = {
  proformaInvoice: "PROFORMA INVOICE",
  commercialInvoice: "COMMERCIAL INVOICE",
  packingList: "PACKING LIST",
  ctn: "CTN",
  netWeight: "NET WEIGHT",
  grossWeight: "GROSS WEIGHT",
  cbm: "CBM",
  shippingMarks: "SHIPPING MARKS",
  to: "To:",
  from: "From:",
  attn: "Attn.",
  tel: "Tel",
  fax: "Fax",
  representative: "Representative",
  faithfully: "Faithfully Yours,",
  date: "DATE",
  refNo: "REF NO",
  orderNo: "PO NO",
  invoiceNo: "INVOICE NO",
  termsOfTrade: "TERMS OF TRADE",
  shipVia: "SHIP VIA",
  delivery: "Delivery",
  paymentTerms: "Payment Terms",
  packing: "Packing",
  validity: "Validity",
  incoterms: "Incoterms",
  remarks: "Remarks",
  commodity: "Commodity",
  descriptionOfGoods: "DESCRIPTION OF GOODS",
  description: "Description",
  hsCode: "HS CODE",
  qty: "QTY",
  unit: "UNIT",
  unitPrice: "PRICE",
  amount: "AMOUNT",
  grandTotal: "GRAND TOTAL",
  total: "Total",
  authorizedSignature: "Authorized Signature",
  bankInfo: "Bank Information",
  bankName: "Bank Name",
  bankSwift: "SWIFT Code",
  accountNo: "Account No.",
  accountee: "Accountee",
  bankAddress: "Bank Address",
  bankTel: "Bank Tel",
  bankFax: "Bank Fax",
} as const;
