/** Fixed English labels for invoice document output (preview, PDF, Excel, print). */
export const INVOICE_DOCUMENT_LABELS = {
  proformaInvoice: "PROFORMA INVOICE",
  to: "Messrs,",
  faithfully: "Faithfully Yours,",
  date: "Date",
  refNo: "Our Ref No.",
  orderNo: "Your Order No.",
  invoiceNo: "Invoice No.",
  delivery: "Delivery",
  paymentTerms: "Payment Terms",
  packing: "Packing",
  validity: "Validity",
  incoterms: "Incoterms",
  remarks: "Remarks",
  commodity: "Commodity",
  description: "Description",
  hsCode: "HS Code",
  qty: "Q'ty",
  unit: "Unit",
  unitPrice: "Unit Price",
  amount: "Amount",
  total: "Total",
  bankInfo: "Bank Information",
  bankName: "Bank Name",
  bankSwift: "SWIFT Code",
  accountNo: "Account No.",
  accountee: "Accountee",
  bankAddress: "Bank Address",
  bankTel: "Bank Tel",
  bankFax: "Bank Fax",
} as const;
